FROM python:3.9-slim
WORKDIR /app
COPY s2_consumidor.py /app
RUN pip install --no-cache-dir \
    kafka-python \
    mysql-connector-python \
    pymongo \
    cassandra-driver
CMD ["python", "s2_consumidor.py"]
